// ════════════════════════════════════════════════════════════════════════════
// AISCERN — Brain of Brains: Ensemble Verdict Engine
// Wires up text-detection-brain + image-detection-brain + all new signals
// ════════════════════════════════════════════════════════════════════════════

import type { ScannedPage, ScannedImage, EnsembleSignals, AIArtifact, SentenceScore } from './types'
import { analyzeStylometry, computeVoiceDiversityIndex, detectStylometricFlag } from './stylometry'
import { analyzeDuplicity, isThinContent } from './duplicity'
import { computePerplexityBurst, computeInformationDensity } from './perplexity'

// ── AI Artifact Detection ──

const LLM_STOP_PHRASES = [
  'i hope this helps',
  "it's important to note",
  'it is important to note',
  'it should be noted',
  'please note that',
  'in conclusion',
  'to summarize',
  'in summary',
  'as an ai',
  'as a language model',
  'i cannot provide',
  'i do not have',
  'my knowledge cutoff',
  'training data',
  'large language model',
  'ai-generated',
  'delve into',
  'tapestry',
  'multifaceted',
  'robust discussion',
  'furthermore',
  'moreover',
  'additionally',
  'consequently',
  'therefore',
  'in light of',
  'it is worth noting',
  'a myriad of',
  'a plethora of',
  'in the ever-evolving landscape',
  'in the realm of',
  'navigating the complexities',
  'underscores the importance',
  'sheds light on',
  'serves as a testament',
  'a testament to',
  'resonate with',
  'at the heart of',
  'a double-edged sword',
  'not unlike',
  'a fine line between',
  'a delicate balance',
]

const PROMPT_RESIDUE_PATTERNS = [
  /\b(?:8k|4k|highly detailed|unreal engine|octane render|vray|cinema 4d|blender render)\b/gi,
  /\b(?:masterpiece|best quality|ultra detailed|hyper realistic|photo realistic)\b/gi,
  /\b(?:dramatic lighting|volumetric lighting|ray tracing|global illumination)\b/gi,
  /\b(?:trending on artstation|deviantart|pixiv|behance)\b/gi,
  /\b(?:made with|created using|generated by)\s+(?:midjourney|dall[\s-]?e|stable diffusion|sdxl|comfyui|leonardo|firefly)\b/gi,
]

const TRANSITION_OVERUSE = [
  'furthermore', 'moreover', 'additionally', 'consequently', 'therefore',
  'however', 'nevertheless', 'nonetheless', 'meanwhile', 'subsequently',
  'in addition', 'on the other hand', 'in contrast', 'similarly', 'likewise',
]

function detectAIArtifacts(text: string): AIArtifact[] {
  const artifacts: AIArtifact[] = []
  const lower = text.toLowerCase()

  // LLM stop phrases
  for (const phrase of LLM_STOP_PHRASES) {
    const regex = new RegExp(`\\b${phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi')
    const matches = text.match(regex)
    if (matches) {
      artifacts.push({
        type: 'phrase',
        evidence: `Found "${matches[0]}" (${matches.length}x)`,
        severity: matches.length > 2 ? 'high' : 'medium',
      })
    }
  }

  // Prompt residue in text
  for (const pattern of PROMPT_RESIDUE_PATTERNS) {
    const matches = text.match(pattern)
    if (matches) {
      artifacts.push({
        type: 'prompt_residue',
        evidence: `Prompt residue: "${matches[0]}"`,
        severity: 'high',
      })
    }
  }

  // Unicode watermarking detection
  const zwChars = (text.match(/[\u200B\u200C\u200D\uFEFF\u2060\u180E]/g) || []).length
  if (zwChars > 0) {
    artifacts.push({
      type: 'watermark',
      evidence: `Found ${zwChars} zero-width characters`,
      severity: zwChars > 5 ? 'high' : 'medium',
    })
  }

  // Transition overuse
  const transitionCounts: Record<string, number> = {}
  for (const trans of TRANSITION_OVERUSE) {
    const regex = new RegExp(`\\b${trans}\\b`, 'gi')
    const count = (text.match(regex) || []).length
    if (count > 0) transitionCounts[trans] = count
  }
  const totalTransitions = Object.values(transitionCounts).reduce((a, b) => a + b, 0)
  const sentenceCount = text.split(/[.!?]+/).filter(s => s.trim().length > 10).length
  const transitionDensity = sentenceCount > 0 ? totalTransitions / sentenceCount : 0

  if (transitionDensity > 0.25) {
    artifacts.push({
      type: 'transition_overuse',
      evidence: `High transition word density: ${(transitionDensity * 100).toFixed(1)}%`,
      severity: transitionDensity > 0.4 ? 'high' : 'medium',
    })
  }

  return artifacts.slice(0, 8)
}

// ── Sentence-Level Scoring ──

function scoreSentences(text: string): SentenceScore[] {
  const sentences = text
    .replace(/\n+/g, ' ')
    .split(/(?<=[.!?])\s+/)
    .map(s => s.trim())
    .filter(s => s.split(/\s+/).length >= 4 && s.length > 30)
    .slice(0, 30)

  if (sentences.length === 0) return []

  // Build simple n-gram model from full text for perplexity
  const fullText = text.toLowerCase().replace(/[^a-z0-9\s]/g, '')
  const ngramCounts: Record<string, number> = {}
  const n = 3
  for (let i = 0; i <= fullText.length - n; i++) {
    const gram = fullText.slice(i, i + n)
    ngramCounts[gram] = (ngramCounts[gram] || 0) + 1
  }
  const totalNgrams = Object.values(ngramCounts).reduce((a, b) => a + b, 0)

  const scores: SentenceScore[] = []

  for (const sentence of sentences) {
    const lower = sentence.toLowerCase()
    let aiScore = 0.3

    // Check for AI phrases
    for (const phrase of LLM_STOP_PHRASES) {
      if (lower.includes(phrase)) {
        aiScore += 0.15
        break
      }
    }

    // Check sentence structure
    const words = sentence.split(/\s+/).filter(Boolean)
    if (words.length > 25) aiScore += 0.05 // AI tends to write longer sentences
    if (words.length < 6) aiScore -= 0.1

    // Check for passive voice
    const passiveIndicators = (sentence.match(/\b(?:is|are|was|were|been|being)\s+\w+ed\b/gi) || []).length
    if (passiveIndicators > 0) aiScore += 0.05 * passiveIndicators

    // Perplexity proxy
    const clean = lower.replace(/[^a-z0-9\s]/g, '')
    let logProb = 0
    let count = 0
    for (let i = 0; i <= clean.length - n; i++) {
      const gram = clean.slice(i, i + n)
      const prob = (ngramCounts[gram] || 0.5) / (totalNgrams || 1)
      logProb += Math.log2(Math.max(0.0001, prob))
      count++
    }
    const perplexity = count > 0 ? Math.pow(2, -logProb / count) : 100

    // Low perplexity = more predictable = more AI-like
    if (perplexity < 20) aiScore += 0.1
    else if (perplexity > 80) aiScore -= 0.1

    scores.push({
      text: sentence.slice(0, 200),
      aiScore: Math.round(Math.min(0.98, Math.max(0.02, aiScore)) * 1000) / 1000,
      perplexity: Math.round(perplexity * 10) / 10,
    })
  }

  return scores
}

// ── Ensemble Scoring ──

interface TextAnalysisInput {
  text: string
  wordCount: number
  contentType: string
  headings: string[]
}

export interface TextAnalysisResult {
  aiScore: number
  verdict: 'AI' | 'HUMAN' | 'UNCERTAIN'
  confidence: number
  ensembleSignals: EnsembleSignals
  topFindings: string[]
  stylometry: ReturnType<typeof analyzeStylometry>
  aiArtifacts: AIArtifact[]
  sentenceScores: SentenceScore[]
  isSpun: boolean
  isThinContent: boolean
  contentDepthScore: number
  perplexityScore: number
}

/**
 * Main text analysis — wires up all engines
 */
export async function analyzeText(
  input: TextAnalysisInput,
  allPagesStylometry?: ReturnType<typeof analyzeStylometry>[]
): Promise<TextAnalysisResult> {
  const { text, wordCount, contentType } = input

  // 1. Stylometry
  const stylometry = analyzeStylometry(text)

  // 2. Perplexity burst
  const perplexityResult = computePerplexityBurst(text)

  // 3. Information density
  const infoDensity = computeInformationDensity(text)

  // 4. AI Artifacts
  const aiArtifacts = detectAIArtifacts(text)

  // 5. Sentence-level scoring
  const sentenceScores = scoreSentences(text)

  // 6. Duplicity (will be computed at site level, placeholder here)
  const isThin = isThinContent(0.5, wordCount) // depth score updated later

  // ── Ensemble Scoring ──

  // Linguistic brain score (heuristic-based)
  let linguisticScore = 0.5

  // Penalize low lexical diversity
  if (stylometry.typeTokenRatio < 0.35) linguisticScore += 0.1
  if (stylometry.typeTokenRatio > 0.55) linguisticScore -= 0.1

  // Penalize low hapax rate
  if (stylometry.hapaxLegomenaRate < 0.25) linguisticScore += 0.1
  if (stylometry.hapaxLegomenaRate > 0.45) linguisticScore -= 0.1

  // Sentence length consistency (AI tends to be more consistent)
  if (stylometry.sentenceLengthCV < 0.2) linguisticScore += 0.08
  if (stylometry.sentenceLengthCV > 0.45) linguisticScore -= 0.08

  // Perplexity signal
  const perplexityScore = perplexityResult.score

  // Information density signal
  const densityScore = infoDensity

  // Artifact density
  const highArtifacts = aiArtifacts.filter(a => a.severity === 'high').length
  const mediumArtifacts = aiArtifacts.filter(a => a.severity === 'medium').length
  const artifactScore = Math.min(0.5, highArtifacts * 0.15 + mediumArtifacts * 0.05)

  // Voice diversity (if available)
  let voiceDiversity = 0.5
  let stylometricFlag = false
  if (allPagesStylometry && allPagesStylometry.length >= 3) {
    voiceDiversity = computeVoiceDiversityIndex(allPagesStylometry)
    stylometricFlag = detectStylometricFlag(allPagesStylometry)
  }

  // Weighted ensemble
  // linguisticBrain: 25%, perplexityBurst: 20%, artifactDensity: 20%,
  // infoDensity: 15%, voiceDiversity: 10%, stylometricFlag: 10%
  const ensembleScore =
    linguisticScore * 0.25 +
    perplexityScore * 0.20 +
    artifactScore * 0.20 +
    densityScore * 0.15 +
    (1 - voiceDiversity) * 0.10 + // low diversity = more AI
    (stylometricFlag ? 0.15 : 0) * 0.10

  const aiScore = Math.min(0.97, Math.max(0.03, ensembleScore))

  // Verdict
  let verdict: 'AI' | 'HUMAN' | 'UNCERTAIN'
  if (aiScore >= 0.65) verdict = 'AI'
  else if (aiScore <= 0.35) verdict = 'HUMAN'
  else verdict = 'UNCERTAIN'

  // Confidence based on signal agreement
  const signals = [linguisticScore, perplexityScore, artifactScore, densityScore]
  const signalVariance = signals.reduce((a, b) => a + Math.pow(b - aiScore, 2), 0) / signals.length
  const confidence = Math.min(0.98, 0.5 + (1 - Math.sqrt(signalVariance)) * 0.5)

  // Top findings
  const topFindings: string[] = []
  if (stylometry.typeTokenRatio < 0.35) topFindings.push(`Low lexical diversity (${stylometry.typeTokenRatio.toFixed(3)})`)
  if (stylometry.hapaxLegomenaRate < 0.25) topFindings.push(`Low hapax legomena rate (${stylometry.hapaxLegomenaRate.toFixed(3)})`)
  if (stylometry.sentenceLengthCV < 0.2) topFindings.push(`Unnaturally consistent sentence lengths`)
  if (perplexityResult.burstiness < 0.1) topFindings.push(`Low perplexity burstiness — AI signature`)
  if (highArtifacts > 0) topFindings.push(`${highArtifacts} high-severity AI artifact${highArtifacts > 1 ? 's' : ''}`)
  if (stylometricFlag) topFindings.push(`Stylometric uniformity across site`)
  if (isThin) topFindings.push(`Thin content detected`)
  if (aiArtifacts.some(a => a.type === 'watermark')) topFindings.push(`Zero-width character watermarking detected`)

  return {
    aiScore: Math.round(aiScore * 1000) / 1000,
    verdict,
    confidence: Math.round(confidence * 1000) / 1000,
    ensembleSignals: {
      hfEnsemble: null, // No HF API in free mode
      linguisticBrain: Math.round(linguisticScore * 1000) / 1000,
      perplexityBurst: Math.round(perplexityScore * 1000) / 1000,
      stylometricFlag,
      isSpun: false, // updated at site level
      isThinContent: isThin,
      voiceDiversity: Math.round(voiceDiversity * 1000) / 1000,
      informationDensity: Math.round(infoDensity * 1000) / 1000,
    },
    topFindings: topFindings.slice(0, 5),
    stylometry,
    aiArtifacts: aiArtifacts.slice(0, 6),
    sentenceScores: sentenceScores.slice(0, 20),
    isSpun: false, // updated at site level
    isThinContent: isThin,
    contentDepthScore: 0, // updated at site level
    perplexityScore: Math.round(perplexityScore * 1000) / 1000,
  }
}

/**
 * Compute site-wide content originality score
 * 0 = all spun, 1 = fully original
 */
export function computeContentOriginality(
  duplicityResults: Record<string, { isSpun: boolean; contentDepthScore: number; similarityToOthers: number }>
): number {
  const pages = Object.values(duplicityResults)
  if (pages.length === 0) return 0.5

  const spunCount = pages.filter(p => p.isSpun).length
  const spunPenalty = spunCount / pages.length

  const avgDepth = pages.reduce((a, p) => a + p.contentDepthScore, 0) / pages.length
  const avgSimilarity = pages.reduce((a, p) => a + p.similarityToOthers, 0) / pages.length

  const originality = (1 - spunPenalty) * 0.4 + avgDepth * 0.4 + (1 - avgSimilarity) * 0.2

  return Math.round(Math.max(0, Math.min(1, originality)) * 1000) / 1000
}
