import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/detect/',
          '/pricing',
          '/enterprise',
          '/compare',
          '/solutions/',
          '/blog',
          '/docs/',
          '/guides',
          '/methodology',
          '/benchmarks',
          '/how-it-works',
          '/research',
          '/transparency',
          '/reviews',
          '/about',
          '/partners',
          '/contact',
          '/faq',
          '/security',
          '/changelog',
          '/roadmap',
          '/status',
          '/chat',
          '/login',
          '/signup',
          '/privacy',
          '/terms',
          '/dpa',
          '/accessibility',
        ],
        disallow: [
          '/dashboard',
          '/history',
          '/profile',
          '/settings',
          '/batch',
          '/scraper',
          '/pipeline',
          '/admin',
          '/api/',
          '/unauthorized',
        ],
      },
    ],
    sitemap: 'https://aiscern.com/sitemap.xml',
    host: 'https://aiscern.com',
  }
}
