import type { Metadata } from 'next'
import { ShieldCheck } from 'lucide-react'
import { SolutionPage } from '@/components/SolutionPage'

export const metadata: Metadata = {
  title: 'AI Detection for Security & Fraud Prevention | Aiscern',
  description: 'Detect voice clones, deepfake videos, synthetic identities and AI-generated phishing content at scale.',
}

export default function SecuritySolutionPage() {
  return (
    <SolutionPage
      industry="Security"
      tagline="Stop Synthetic Threats Before They Land"
      description="Aiscern gives security and fraud teams a multi-modal detection layer for voice clones, deepfake video, synthetic identities and AI-generated phishing — before they reach customers or systems."
      icon={<ShieldCheck className="w-16 h-16" />}
      color="#dc2626"
      heroImage="/solutions/hero-security.jpg"
      actionImage="/solutions/action-security.jpg"
      stats={[
        { value: '~79%', label: 'Audio deepfake detection' },
        { value: '~82%', label: 'Image/video forensics' },
        { value: 'API', label: 'Integration available' },
      ]}
      painPoints={[
        {
          problem: 'Voice-cloned audio used to bypass phone-based identity verification.',
          solution: 'Audio deepfake detector analyses waveform patterns and prosody anomalies in real time.',
        },
        {
          problem: 'Synthetic identity documents generated by AI flooding onboarding pipelines.',
          solution: 'Image forensics detects AI-generated ID photos and manipulated document fields.',
        },
        {
          problem: 'AI-written phishing emails that evade keyword-based spam filters.',
          solution: 'Text detection flags suspiciously fluent, formula-following phishing prose.',
        },
        {
          problem: 'Deepfake executive videos used in BEC (Business Email Compromise) attacks.',
          solution: 'Video frame analysis and audio-sync anomaly detection flags synthetic executive impersonations.',
        },
      ]}
      useCases={[
        { title: 'KYC Document Verification', desc: 'Check identity document photos for AI generation before customer onboarding approval.' },
        { title: 'Voice Authentication Audit', desc: 'Scan call-centre recordings for voice cloning attempts against customer profiles.' },
        { title: 'Phishing Content Detection', desc: 'Flag AI-generated phishing emails and social engineering scripts before they reach staff.' },
        { title: 'Deepfake Video Analysis', desc: 'Detect deepfake executive communications used in BEC and wire fraud schemes.' },
        { title: 'Social Media Impersonation', desc: 'Verify profile images and content authenticity to detect synthetic impostor accounts.' },
        { title: 'API-Level Integration', desc: 'Integrate detection into your fraud pipeline via the Aiscern REST API.' },
      ]}
      ctaHref="/detect/image"
      ctaLabel="Scan for Deepfakes"
      toolName="Multi-Modal Detector"
    />
  )
}
