import type { Metadata } from 'next'
import { Users } from 'lucide-react'
import { SolutionPage } from '@/components/SolutionPage'

export const metadata: Metadata = {
  title: 'AI Detection for HR & Recruiting | Aiscern',
  description: 'Screen AI-polished CVs, cover letters and video transcripts before they reach your hiring panel.',
}

export default function HRSolutionPage() {
  return (
    <SolutionPage
      industry="HR & Recruiting"
      tagline="Hire the Real Candidate, Not Their AI"
      description="Aiscern helps HR teams and recruiters spot AI-generated CVs, cover letters and interview prep responses — so you evaluate actual candidates, not their tools."
      icon={<Users className="w-16 h-16" />}
      color="#0891b2"
      heroImage="/solutions/hero-hr.jpg"
      actionImage="/solutions/action-hr.jpg"
      stats={[
        { value: '~85%', label: 'CV text detection' },
        { value: '~76%', label: 'Video transcript scan' },
        { value: '<5s',  label: 'Per document' },
      ]}
      painPoints={[
        {
          problem: 'AI-polished CVs mask the real candidate behind flawless, generic prose.',
          solution: 'Scan written applications for AI probability — highlight sections likely generated vs genuinely authored.',
        },
        {
          problem: 'Cover letters all sound identical — impossible to assess authentic motivation.',
          solution: 'Linguistic fingerprint analysis flags suspiciously uniform phrasing across multiple applicants.',
        },
        {
          problem: 'Video interview transcripts generated by AI coaching tools create false impressions.',
          solution: 'Paste or upload transcripts for AI detection before scoring responses.',
        },
        {
          problem: 'No documentation if a candidate disputes a rejection based on AI use.',
          solution: 'Timestamped, shareable reports give HR a defensible audit trail.',
        },
      ]}
      useCases={[
        { title: 'CV Screening', desc: 'Paste or upload CVs for AI probability scoring before shortlisting.' },
        { title: 'Cover Letter Review', desc: 'Detect templated, AI-written cover letters across your applicant pool.' },
        { title: 'Interview Transcript Audit', desc: 'Scan video interview transcripts for AI-coached responses.' },
        { title: 'Batch Applicant Scan', desc: 'Process up to 20 documents at once during high-volume hiring cycles.' },
        { title: 'Assessment Response Check', desc: 'Verify written task responses submitted as part of skills assessments.' },
        { title: 'Onboarding Document Audit', desc: 'Check post-hire documentation for authenticity before finalising contracts.' },
      ]}
      ctaHref="/detect/text"
      ctaLabel="Scan a CV Now"
      toolName="AI Text Detector"
    />
  )
}
