/**
 * Aiscern Image v3 — LLM Vision Judges (Gemini + Grok)
 * Structured prompt engineering for AI image forensic analysis.
 * NEW FILE — does not modify existing gemini-analyzer.ts.
 */

export interface LLMVerdictV3 {
  is_ai_generated: boolean;
  confidence: number;
  reasoning: string;
  artifact_flags: string[];
  physical_inconsistencies: string[];
  generator_guess: string | null;
}

const GEMINI_IMAGE_PROMPT_V3 = `You are an expert forensic image analyst specializing in AI-generated image detection.
Analyze the provided image and determine if it was generated by AI (diffusion model, GAN, or other synthetic method) or if it is a real photograph.

Look for these specific artifacts and inconsistencies:
1. ANATOMICAL ISSUES: Extra fingers, malformed hands, asymmetric eyes, impossible body proportions, blurry facial features
2. TEXT RENDERING: Garbled text, nonsensical characters, blurry signs, misspelled words in images
3. PHYSICAL IMPOSSIBILITIES: Objects floating, impossible shadows, inconsistent lighting directions, water flowing uphill, glass not reflecting correctly
4. PATTERN ARTIFACTS: Repeating patterns, grid-like textures, strange fabric/weave patterns, watermarks that look like artifacts
5. BACKGROUND ISSUES: Blurry backgrounds with sharp foregrounds (or vice versa), objects bleeding into each other, inconsistent depth of field
6. SKIN & HAIR: Overly smooth skin, hair that does not follow physics, strange ear shapes, glassy eyes without catchlights
7. OBJECT BOUNDARIES: Fuzzy edges between objects, objects merging unnaturally, transparent solid objects
8. REFLECTIONS & REFRACTIONS: Mirrors showing wrong reflections, glasses not distorting correctly, water reflections inconsistent

Respond ONLY in valid JSON format with this exact structure:
{
  "is_ai_generated": true/false,
  "confidence": 0.0-1.0,
  "reasoning": "detailed explanation of findings",
  "artifact_flags": ["list", "of", "specific", "artifacts", "found"],
  "physical_inconsistencies": ["list", "of", "physical", "impossibilities"],
  "generator_guess": "Stable Diffusion/DALL-E/Midjourney/FLUX/GAN/Unknown or null"
}

If you are uncertain, set confidence below 0.7 and is_ai_generated to false.`;

const GROK_IMAGE_PROMPT_V3 = `Analyze this image forensically. Determine if it is AI-generated or authentic.

Focus on:
- Subtle artifacts invisible to casual observers
- Statistical anomalies in noise patterns
- Compression artifact consistency
- Metadata plausibility indicators
- Generator-specific fingerprints (if identifiable)

Return JSON:
{
  "is_ai_generated": boolean,
  "confidence": 0.0-1.0,
  "forensic_notes": "technical observations",
  "suspicious_regions": ["description of suspicious areas"],
  "generator_guess": "model name or null"
}`;

export async function queryGeminiVisionV3(
  imageBase64: string,
  apiKey: string
): Promise<LLMVerdictV3> {
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: GEMINI_IMAGE_PROMPT_V3 },
              {
                inline_data: {
                  mime_type: "image/jpeg",
                  data: imageBase64,
                },
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.1,
          maxOutputTokens: 1024,
          responseMimeType: "application/json",
        },
      }),
    }
  );

  if (!response.ok) {
    throw new Error(`Gemini API error: ${response.status}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  try {
    return JSON.parse(text) as LLMVerdictV3;
  } catch {
    return {
      is_ai_generated: false,
      confidence: 0.5,
      reasoning: "Failed to parse structured response",
      artifact_flags: [],
      physical_inconsistencies: [],
      generator_guess: null,
    };
  }
}

export async function queryGrokVisionV3(
  imageBase64: string,
  apiKey: string
): Promise<LLMVerdictV3> {
  const response = await fetch("https://api.x.ai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: "grok-2-vision-latest",
      messages: [
        {
          role: "user",
          content: [
            { type: "text", text: GROK_IMAGE_PROMPT_V3 },
            {
              type: "image_url",
              image_url: { url: `data:image/jpeg;base64,${imageBase64}` },
            },
          ],
        },
      ],
      temperature: 0.1,
      max_tokens: 1024,
    }),
  });

  if (!response.ok) {
    throw new Error(`Grok API error: ${response.status}`);
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;

  try {
    return JSON.parse(text) as LLMVerdictV3;
  } catch {
    return {
      is_ai_generated: false,
      confidence: 0.5,
      reasoning: "Failed to parse Grok response",
      artifact_flags: [],
      physical_inconsistencies: [],
      generator_guess: null,
    };
  }
}
