import type { Metadata } from 'next'
import { SolutionPage } from '@/components/SolutionPage'
import { Scale, FileSearch, BarChart3, Shield, Brain, Lock, CheckCircle, AlertTriangle } from 'lucide-react'

export const metadata: Metadata = {
  title: 'AI Detection for Legal & Compliance — Aiscern',
  description: 'Verify authorship of legal documents, contracts, and evidence. Forensic-grade AI detection with exportable audit reports for legal proceedings.',
  openGraph: {
    title: 'AI Detection for Legal & Compliance — Aiscern',
    url: 'https://aiscern.com/solutions/legal',
    siteName: 'Aiscern',
  },
}

export default function LegalPage() {
  return (
    <SolutionPage
      industry="Legal & Compliance"
      tagline="Catch Hallucinated Citations Before Filing"
      description="In Mata v. Avianca (S.D.N.Y. 2023), a lawyer submitted six fabricated cases generated by ChatGPT and was sanctioned by the court. Aiscern's document ensemble flags AI-generated sections in briefs and contracts with a timestamped, court-referenceable report."
      heroIcon={<Scale className="w-20 h-20 lg:w-28 lg:h-28 opacity-80" strokeWidth={1} />}
      accentColor="emerald"
      ctaLabel="Start Free Legal Account"
      heroImage="/solutions/legal/hero.webp"
      heroImageAlt="A senior law firm partner at a mahogany desk reviewing a document with a magnifying glass, legal papers spread across the surface"
      problemImage="/solutions/legal/problem.webp"
      problemImageAlt="A legal brief with a section circled in red, paperclipped to a detection report, illustrating a flagged citation before filing"
      trustBar={[
        { label: 'Ensemble AUC', value: '≥96%' },
        { label: 'Report Format', value: 'Timestamped PDF' },
        { label: 'Chain of Custody', value: 'Logged' },
      ]}
      workflow={[
        { title: 'Upload Brief or Contract', desc: 'Submit the document ahead of filing or execution.' },
        { title: 'Run Citation & Text Analysis', desc: 'The ensemble flags AI-generated passages and irregular citation patterns.' },
        { title: 'Export Court-Ready Report', desc: 'Download a timestamped PDF with model breakdown and document hash.' },
      ]}
      comparisonCompetitorName="Manual bluebooking"
      comparisonRows={[
        { feature: 'Review time per 30-page brief', aiscern: 'Minutes', competitor: 'Hours' },
        { feature: 'Timestamped audit log', aiscern: true, competitor: false },
        { feature: 'Sentence-level flagging', aiscern: true, competitor: false },
        { feature: 'Document hash for chain of custody', aiscern: true, competitor: false },
        { feature: 'Scales to firm-wide review', aiscern: true, competitor: false },
      ]}
      problemTitle="Hallucinated Citations Reach Filing"
      painPoints={[
        { title: 'AI-hallucinated citations in legal briefs', desc: 'Attorneys have submitted briefs with fabricated case citations generated by LLMs. Courts have sanctioned lawyers for unverified AI output.' },
        { title: 'Contract authenticity disputes', desc: 'AI-drafted contracts may contain subtle inconsistencies not obvious to human review. Establishing original authorship is increasingly complex.' },
        { title: 'Evidence integrity challenges', desc: 'Deepfake audio, synthetic video, and AI-generated documents are being submitted as evidence, requiring new verification capabilities.' },
        { title: 'Regulatory compliance documentation risk', desc: 'AI-generated compliance reports and filings that don\'t reflect genuine organizational analysis create significant liability exposure.' },
      ]}
      features={[
        { icon: <Brain className="w-5 h-5" />, title: 'Multi-Model Ensemble', desc: 'RoBERTa + Binoculars + Gemini ensemble detects AI text across legal drafting styles with ≥96% AUC.' },
        { icon: <FileSearch className="w-5 h-5" />, title: 'Document-Level Analysis', desc: 'Analyze full legal documents including briefs, contracts, affidavits, and compliance filings.' },
        { icon: <Lock className="w-5 h-5" />, title: 'Forensic PDF Reports', desc: 'Timestamped, scan-ID-stamped PDF reports with model confidence breakdown. Exportable for court submission.' },
        { icon: <CheckCircle className="w-5 h-5" />, title: 'Chain of Custody Logging', desc: 'Every scan generates an immutable log entry with user ID, timestamp, document hash, and verdict.' },
        { icon: <Shield className="w-5 h-5" />, title: 'Data Security', desc: 'Enterprise plans support private deployment options and enhanced data handling for privileged legal material.' },
        { icon: <BarChart3 className="w-5 h-5" />, title: 'Sentence-Level Audit', desc: 'Pinpoint which sections of a document are AI-flagged — not just a document-level score — for targeted human review.' },
      ]}
      useCases={[
        {
          title: 'Brief & Filing Verification',
          challenge: 'A law firm\'s quality control process needs to catch hallucinated citations in externally prepared briefs before filing.',
          action: 'Every brief runs through Aiscern as a standard pre-filing step.',
          outcome: 'Flagged citations checked and corrected before the court ever sees them',
        },
        {
          title: 'Evidence Authentication',
          challenge: 'A litigation team receives audio evidence from opposing counsel and needs to check for synthesis.',
          action: 'The audio pipeline analyzes spectral characteristics for voice-clone artifacts.',
          outcome: 'Suspect audio flagged for expert witness follow-up',
        },
        {
          title: 'Compliance Documentation Audit',
          challenge: 'A financial institution\'s compliance officer needs to verify external consultants\' analysis is genuine.',
          action: 'Quarterly reports are scanned before sign-off.',
          outcome: 'LLM-generated filler sections identified before submission to regulators',
        },
      ]}
      caseStudy={{
        quote: '[QUOTE TEXT HERE]',
        author: '[CUSTOMER NAME]',
        role: '[ROLE]',
        company: '[COMPANY]',
        metric: '[METRIC]',
        metricLabel: 'Placeholder metric',
        isPlaceholder: true,
      }}
      faqs={[
        { q: 'Are Aiscern reports admissible in legal proceedings?', a: 'Our reports are designed to be audit-trail documents, not expert witness testimony. They provide technical evidence that supports — not replaces — expert analysis. Consult with your legal team on jurisdiction-specific admissibility.' },
        { q: 'Can Aiscern detect AI text in legal documents with heavy boilerplate?', a: 'Legal documents contain significant boilerplate that may appear in AI training data. Our ensemble is tuned to distinguish genuine AI generation from standard legal language. Confidence scores below 62% indicate ambiguous sections.' },
        { q: 'What security certifications does Aiscern hold?', a: 'We are actively working toward SOC 2 Type II compliance. Current security measures are documented at /security. Enterprise clients can request our security assessment documentation.' },
        { q: 'Is there attorney-client privilege protection for submitted documents?', a: 'Documents are processed ephemerally — not stored beyond the session unless you explicitly save a report. We do not train on submitted content. For privileged material, we recommend our Enterprise plan with enhanced data handling agreements.' },
        { q: 'Can we run detection on documents in languages other than English?', a: 'English, Spanish, French, German, and Portuguese are supported with high accuracy. Other languages may return results in the uncertain confidence range. Legal documents in non-supported languages are best verified with English translation first.' },
      ]}
    />
  )
}
