// ════════════════════════════════════════════════════════════════════════════
// AISCERN — Layer 9: Contradiction Graph + Generator Attribution
//
// Two jobs:
//
//   1. CONTRADICTION RESOLUTION
//      When agent A says 0.85 AI and agent B says 0.15 AI, this resolves which
//      evidence wins based on evidence type hierarchy, definitiveness, and
//      confidence. Hard-gate definitive findings (wrong finger count, incoherent
//      text, impossible shadows) override weaker signals.
//
//   2. GENERATOR ATTRIBUTION
//      Aggregates votes from generator-specialist agents + image brain signals
//      to produce a probability table: "most likely generated by FLUX.1 (72%)"
//
// This layer does NOT call any vision API — it's pure math on existing outputs.
// ════════════════════════════════════════════════════════════════════════════

import type { SemanticAgentReport, LayerReport } from '@/types/forensic'

// ── Evidence node (internal, richer than the types/forensic.ts EvidenceNode) ─

export interface GraphEvidenceNode {
  agentId:       string
  score:         number
  confidence:    number
  claim:         string
  evidenceType:  'anatomical' | 'physics' | 'generator' | 'frequency' | 'texture' | 'semantic' | 'perspective'
  isDefinitive:  boolean
  definitiveReason?: string
}

// ── Contradiction record ──────────────────────────────────────────────────────

export interface Contradiction {
  nodeA:        GraphEvidenceNode
  nodeB:        GraphEvidenceNode
  conflictType: 'direct_opposition' | 'indirect_inconsistency'
  resolution:   'a_wins' | 'b_wins' | 'both_uncertain'
  explanation:  string
}

// ── Generator attribution ─────────────────────────────────────────────────────

export interface GeneratorAttribution {
  topCandidate:    string
  probability:     number
  evidence:        string[]
  alternatives:    Array<{ name: string; probability: number }>
  isReal:          boolean
}

// ── Contradiction Graph output ────────────────────────────────────────────────

export interface ContradictionGraphResult {
  adjustedScore:        number        // Bayesian score adjusted after contradiction resolution
  definitiveOverride:   boolean       // True if a definitive gate fired
  definitiveReason:     string | null // e.g. "Wrong finger count detected by HandAnatomyAgent"
  contradictions:       Contradiction[]
  resolvedNodes:        GraphEvidenceNode[]
  generatorAttribution: GeneratorAttribution
  confidenceInterval:   [number, number]
  layerReport:          LayerReport
}

// ── Definitive AI gates ───────────────────────────────────────────────────────
// These findings alone set the verdict regardless of other evidence.

interface DefinitiveGate {
  agentNamePattern: RegExp
  scoreThreshold:   number
  reason:           string
}

const DEFINITIVE_AI_GATES: DefinitiveGate[] = [
  {
    agentNamePattern: /hand.*anatomy|HandAnatomy/i,
    scoreThreshold:   0.85,
    reason:           'Hand anatomy failure — wrong finger count or impossible joints detected',
  },
  {
    agentNamePattern: /text.*forensics|TextForensics/i,
    scoreThreshold:   0.90,
    reason:           'Completely incoherent text detected — pseudo-text/letter soup found',
  },
  {
    agentNamePattern: /eye.*anatomy|EyeAnatomy/i,
    scoreThreshold:   0.90,
    reason:           'Eye physics impossible — iris symmetry or catchlight mismatch confirmed',
  },
  {
    agentNamePattern: /shadow.*geometry|ShadowGeometry/i,
    scoreThreshold:   0.88,
    reason:           'Shadow geometry physically impossible — multiple impossible shadow origins',
  },
  {
    agentNamePattern: /gemini.*specialist|GeminiSpecialist/i,
    scoreThreshold:   0.85,
    reason:           'Gemini/Imagen 3 generator-specific tells definitively identified',
  },
  {
    agentNamePattern: /dalle.*specialist|DalleSpecialist/i,
    scoreThreshold:   0.85,
    reason:           'DALL-E 3 / GPT-4o generator-specific tells definitively identified',
  },
  {
    agentNamePattern: /flux.*specialist|FluxSpecialist/i,
    scoreThreshold:   0.85,
    reason:           'FLUX generator-specific tells definitively identified',
  },
  {
    agentNamePattern: /gravity.*validator|GravityValidator/i,
    scoreThreshold:   0.92,
    reason:           'Object defying gravity with no support mechanism — physically impossible scene',
  },
]

// ── Evidence type hierarchy (higher = wins in conflicts) ─────────────────────

const EVIDENCE_TYPE_WEIGHT: Record<string, number> = {
  anatomical:  5,
  physics:     4,
  frequency:   3,
  generator:   3,
  texture:     2,
  perspective: 2,
  semantic:    1,
}

// ── Map agent name → evidence type ───────────────────────────────────────────

function inferEvidenceType(agentName: string): GraphEvidenceNode['evidenceType'] {
  const name = agentName.toLowerCase()
  if (/hand|eye|face.*bound|body.*prop|anatomy/i.test(name))   return 'anatomical'
  if (/shadow|gravity|fluid|motion.*blur|specular|material|physics|scene.*phys/i.test(name)) return 'physics'
  if (/frequency|noise.*stat/i.test(name))                      return 'frequency'
  if (/gemini.*spec|dalle.*spec|flux.*spec|generator.*finger/i.test(name)) return 'generator'
  if (/micro.*texture|material/i.test(name))                    return 'texture'
  if (/top.*down|ground.*level|macro|wide.*context|bg.*fg/i.test(name)) return 'perspective'
  return 'semantic'
}

// ── Build graph nodes from all agent outputs ──────────────────────────────────

function buildGraphNodes(
  allAgents:        SemanticAgentReport[],
  physicsDefinitive: Array<{ agentName: string; score: number; reason: string }>,
): GraphEvidenceNode[] {
  const definitiveAgentNames = new Set(physicsDefinitive.map(d => d.agentName))
  const definitiveReasonMap  = new Map(physicsDefinitive.map(d => [d.agentName, d.reason]))

  return allAgents.map(agent => {
    // Check if any definitive gate fires for this agent
    let isDefinitive      = definitiveAgentNames.has(agent.agentName)
    let definitiveReason: string | undefined

    if (!isDefinitive) {
      for (const gate of DEFINITIVE_AI_GATES) {
        if (gate.agentNamePattern.test(agent.agentName) && agent.agentSuspicionScore >= gate.scoreThreshold) {
          isDefinitive    = true
          definitiveReason = gate.reason
          break
        }
      }
    } else {
      definitiveReason = definitiveReasonMap.get(agent.agentName)
    }

    const topEvidence = agent.evidence
      .filter(e => e.status === 'anomalous')
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, 1)
      .map(e => e.detail)
      .join('; ')

    return {
      agentId:         agent.agentName,
      score:           agent.agentSuspicionScore,
      confidence:      agent.agentSuspicionScore,
      claim:           topEvidence || agent.rawResponse.slice(0, 120),
      evidenceType:    inferEvidenceType(agent.agentName),
      isDefinitive,
      definitiveReason,
    }
  })
}

// ── Contradiction detector ────────────────────────────────────────────────────

function detectContradictions(nodes: GraphEvidenceNode[]): Contradiction[] {
  const contradictions: Contradiction[] = []
  const OPPOSITION_THRESHOLD = 0.35 // Difference this large = direct opposition

  for (let i = 0; i < nodes.length; i++) {
    for (let j = i + 1; j < nodes.length; j++) {
      const a = nodes[i]
      const b = nodes[j]
      const diff = Math.abs(a.score - b.score)

      if (diff < OPPOSITION_THRESHOLD) continue

      const conflictType: Contradiction['conflictType'] =
        diff >= 0.50 ? 'direct_opposition' : 'indirect_inconsistency'

      // High scorer is A, low scorer is B for resolution logic
      const [high, low] = a.score >= b.score ? [a, b] : [b, a]

      let resolution: Contradiction['resolution']
      let explanation: string

      // Rule 1: Definitive beats non-definitive always
      if (high.isDefinitive && !low.isDefinitive) {
        resolution  = 'a_wins'
        explanation = `${high.agentId} is definitive (${high.definitiveReason ?? 'hard gate'}); overrides ${low.agentId}`
      }
      // Rule 2: Higher evidence type wins by >=2 tiers
      else if (
        EVIDENCE_TYPE_WEIGHT[high.evidenceType] >=
        EVIDENCE_TYPE_WEIGHT[low.evidenceType] + 2
      ) {
        resolution  = 'a_wins'
        explanation = `${high.evidenceType} evidence outranks ${low.evidenceType} evidence by ≥2 tiers`
      }
      // Rule 3: Same type, confidence spread > 0.2
      else if (high.confidence > low.confidence + 0.20) {
        resolution  = 'a_wins'
        explanation = `${high.agentId} has confidence ${high.confidence.toFixed(2)} vs ${low.confidence.toFixed(2)} — higher confidence wins`
      }
      // Rule 4: Truly uncertain — both get penalized
      else {
        resolution  = 'both_uncertain'
        explanation = `${high.agentId} (${high.score.toFixed(2)}) and ${low.agentId} (${low.score.toFixed(2)}) conflict without clear resolution — both weighted down 30%`
      }

      contradictions.push({
        nodeA:        high,
        nodeB:        low,
        conflictType,
        resolution,
        explanation,
      })
    }
  }

  return contradictions
}

// ── Apply contradiction resolutions to get final resolved nodes ───────────────

function applyContradictionResolutions(
  nodes:         GraphEvidenceNode[],
  contradictions: Contradiction[],
): { resolvedNodes: GraphEvidenceNode[]; penalizedAgents: Set<string> } {
  const penalizedAgents = new Set<string>()

  for (const contradiction of contradictions) {
    if (contradiction.resolution === 'both_uncertain') {
      penalizedAgents.add(contradiction.nodeA.agentId)
      penalizedAgents.add(contradiction.nodeB.agentId)
    }
    // 'a_wins' means nodeB evidence is effectively discounted
    // The loser's score gets pulled toward 0.5 in the adjustment
  }

  const resolvedNodes = nodes.map(node => {
    if (!penalizedAgents.has(node.agentId)) return node
    // Penalized: pull 30% toward 0.5
    return { ...node, score: node.score * 0.70 + 0.50 * 0.30 }
  })

  return { resolvedNodes, penalizedAgents }
}

// ── Generator attribution builder ─────────────────────────────────────────────

const GENERATOR_NAMES = [
  'Gemini / Imagen 3',
  'DALL-E 3',
  'GPT-4o Native',
  'FLUX.1 (dev/schnell/pro)',
  'Midjourney v5/v6',
  'Stable Diffusion XL',
  'Grok / Aurora',
  'Adobe Firefly',
  'Sora / Video Frame',
  'Unknown AI Generator',
  'Real Photograph',
] as const

type GeneratorName = typeof GENERATOR_NAMES[number]

interface GeneratorVotes {
  [key: string]: number
}

function buildGeneratorAttribution(
  nodes:          GraphEvidenceNode[],
  allAgents:      SemanticAgentReport[],
): GeneratorAttribution {
  const votes: GeneratorVotes = Object.fromEntries(GENERATOR_NAMES.map(g => [g, 0]))

  for (const agent of allAgents) {
    const s = agent.agentSuspicionScore

    // Generator specialist agents cast primary votes
    if (/GeminiSpecialist|gemini.*specialist/i.test(agent.agentName)) {
      votes['Gemini / Imagen 3']    += s * 3.0
    }
    if (/DalleSpecialist|dalle.*specialist/i.test(agent.agentName)) {
      // Distinguish DALL-E 3 vs GPT-4o by looking for GPT-4o specific tells in evidence
      const hasGpt4oTell = agent.evidence.some(e =>
        /gpt.?4o|eyebrow|nasolabial|microexpression/i.test(e.detail)
      )
      votes[hasGpt4oTell ? 'GPT-4o Native' : 'DALL-E 3'] += s * 3.0
    }
    if (/FluxSpecialist|flux.*specialist/i.test(agent.agentName)) {
      votes['FLUX.1 (dev/schnell/pro)'] += s * 3.0
    }

    // Generator fingerprint agent — look at its raw response for named generators
    if (/GeneratorFingerprint|generator.*finger/i.test(agent.agentName)) {
      const raw = (agent as any).topGeneratorMatch as string | undefined
      if (raw) {
        const match = GENERATOR_NAMES.find(g =>
          g.toLowerCase().includes(raw.toLowerCase().split(/\s/)[0])
        )
        if (match) votes[match] += s * 2.0
      }
      votes['Unknown AI Generator'] += s * 0.5 // fallback
    }

    // Color science agent — channel bias patterns
    const ext = agent as any
    if (ext.generatorColorMatch) {
      const colorMatch = String(ext.generatorColorMatch)
      if (/gemini|imagen/i.test(colorMatch))      votes['Gemini / Imagen 3']          += s * 1.5
      if (/dalle|dall.e/i.test(colorMatch))        votes['DALL-E 3']                   += s * 1.5
      if (/flux/i.test(colorMatch))                votes['FLUX.1 (dev/schnell/pro)']   += s * 1.5
      if (/midjourney|mj/i.test(colorMatch))       votes['Midjourney v5/v6']           += s * 1.5
      if (/stable.*diff|sdxl/i.test(colorMatch))   votes['Stable Diffusion XL']        += s * 1.5
      if (/firefly/i.test(colorMatch))             votes['Adobe Firefly']               += s * 1.5
    }

    // Low overall AI scores vote for real photograph
    if (s < 0.35) {
      votes['Real Photograph'] += (0.35 - s) * 2.0
    }
  }

  // Find top candidate
  const totalVotes = Object.values(votes).reduce((a, b) => a + b, 0) || 1
  const sorted     = Object.entries(votes).sort((a, b) => b[1] - a[1])
  const topName    = sorted[0][0] as GeneratorName
  const topProb    = Math.min(0.98, sorted[0][1] / totalVotes)

  const alternatives = sorted.slice(1, 4)
    .filter(([, v]) => v > 0)
    .map(([name, v]) => ({ name, probability: Math.min(0.98, v / totalVotes) }))

  // Collect top evidence sentences
  const evidence: string[] = []
  for (const agent of allAgents) {
    for (const ev of agent.evidence) {
      if (ev.status === 'anomalous' && ev.confidence > 0.75) {
        evidence.push(`[${agent.agentName}] ${ev.detail}`)
        if (evidence.length >= 4) break
      }
    }
    if (evidence.length >= 4) break
  }

  return {
    topCandidate: topName,
    probability:  topProb,
    evidence,
    alternatives,
    isReal: topName === 'Real Photograph',
  }
}

// ── Bootstrap confidence interval ────────────────────────────────────────────

function computeConfidenceInterval(
  scores:  number[],
  weights: number[],
): [number, number] {
  if (scores.length === 0) return [0.3, 0.7]

  const N = 500 // bootstrap samples (reduced for cost)
  const bootstrapMeans: number[] = []

  for (let i = 0; i < N; i++) {
    let wSum = 0, wMean = 0
    for (let j = 0; j < scores.length; j++) {
      // Sample with replacement (weighted)
      const idx = Math.floor(Math.random() * scores.length)
      wMean += scores[idx] * (weights[idx] ?? 1)
      wSum  += weights[idx] ?? 1
    }
    bootstrapMeans.push(wMean / (wSum || 1))
  }
  bootstrapMeans.sort((a, b) => a - b)

  const lo = bootstrapMeans[Math.floor(N * 0.025)]
  const hi = bootstrapMeans[Math.floor(N * 0.975)]
  return [
    Math.min(Math.max(lo, 0), 1),
    Math.min(Math.max(hi, 0), 1),
  ]
}

// ── Adjusted score computation ────────────────────────────────────────────────
// Takes the Bayesian score from final-fusion and adjusts it based on:
// 1. Definitive gate overrides
// 2. Contradiction resolutions (penalized agents)

function computeAdjustedScore(
  bayesianScore:  number,
  resolvedNodes:  GraphEvidenceNode[],
  definitiveOverride: boolean,
): number {
  if (definitiveOverride) {
    // Definitive gate fired: clamp to 0.90+ or 0.10- depending on direction
    // (All current definitive gates are AI detections)
    return Math.max(bayesianScore, 0.90)
  }

  // Recompute weighted average from resolved nodes
  const aiNodes   = resolvedNodes.filter(n => n.score > 0.5)
  const realNodes = resolvedNodes.filter(n => n.score <= 0.5)

  if (resolvedNodes.length === 0) return bayesianScore

  const resolvedAvg = resolvedNodes.reduce((s, n) => s + n.score, 0) / resolvedNodes.length

  // Blend Bayesian (70%) with resolved average (30%)
  const blended = bayesianScore * 0.70 + resolvedAvg * 0.30

  // If most nodes agree (low variance), nudge toward consensus
  const variance = resolvedNodes.reduce((s, n) => s + (n.score - resolvedAvg) ** 2, 0) / resolvedNodes.length
  if (variance < 0.02 && resolvedNodes.length >= 4) {
    return resolvedAvg * 0.50 + blended * 0.50
  }

  return blended
}

// ── Main Entry Point ──────────────────────────────────────────────────────────

export interface ContradictionGraphInput {
  bayesianScore:     number
  l6Agents:          SemanticAgentReport[]   // All 20 L6 agents
  l7Agents:          SemanticAgentReport[]   // 5 perspective agents
  l8Agents:          SemanticAgentReport[]   // 7 physics/biology agents
  l8Definitive:      Array<{ agentName: string; score: number; reason: string }>
}

export function runContradictionGraph(input: ContradictionGraphInput): ContradictionGraphResult {
  const start     = Date.now()
  const allAgents = [...input.l6Agents, ...input.l7Agents, ...input.l8Agents]

  if (allAgents.length === 0) {
    return {
      adjustedScore:        input.bayesianScore,
      definitiveOverride:   false,
      definitiveReason:     null,
      contradictions:       [],
      resolvedNodes:        [],
      generatorAttribution: {
        topCandidate: 'Unknown AI Generator',
        probability:  0.5,
        evidence:     [],
        alternatives: [],
        isReal:       false,
      },
      confidenceInterval: [Math.max(0, input.bayesianScore - 0.15), Math.min(1, input.bayesianScore + 0.15)],
      layerReport: {
        layer:               22,
        layerName:           'Contradiction Graph (L9)',
        processingTimeMs:    Date.now() - start,
        status:              'failure',
        evidence:            [],
        layerSuspicionScore: input.bayesianScore,
      },
    }
  }

  // Build graph nodes from all agents
  const nodes = buildGraphNodes(allAgents, input.l8Definitive)

  // Detect contradictions
  const contradictions = detectContradictions(nodes)

  // Apply resolutions
  const { resolvedNodes, penalizedAgents } = applyContradictionResolutions(nodes, contradictions)

  // Check for definitive override
  const definitiveNode = resolvedNodes.find(n => n.isDefinitive && n.score >= 0.85)
  const definitiveOverride = !!definitiveNode
  const definitiveReason   = definitiveNode?.definitiveReason ?? null

  // Compute adjusted score
  const adjustedScore = computeAdjustedScore(input.bayesianScore, resolvedNodes, definitiveOverride)

  // Build generator attribution from all agents
  const generatorAttribution = buildGeneratorAttribution(nodes, allAgents)

  // Confidence interval from resolved scores + equal weights
  const scores  = resolvedNodes.map(n => n.score)
  const weights = resolvedNodes.map(() => 1.0)
  const confidenceInterval = computeConfidenceInterval(scores, weights)

  return {
    adjustedScore:      Math.min(1, Math.max(0, adjustedScore)),
    definitiveOverride,
    definitiveReason,
    contradictions,
    resolvedNodes,
    generatorAttribution,
    confidenceInterval,
    layerReport: {
      layer:               22,
      layerName:           'Contradiction Graph (L9)',
      processingTimeMs:    Date.now() - start,
      status:              'success',
      evidence:            resolvedNodes
        .filter(n => n.isDefinitive || n.score > 0.75 || n.score < 0.25)
        .map(n => ({
          layer:        22,
          category:     n.evidenceType,
          artifactType: n.agentId,
          status:       (n.score > 0.65 ? 'anomalous' : n.score < 0.35 ? 'normal' : 'inconclusive') as 'anomalous' | 'normal' | 'inconclusive',
          confidence:   n.score,
          detail:       n.claim.slice(0, 180),
        })),
      layerSuspicionScore: Math.min(1, Math.max(0, adjustedScore)),
    },
  }
}
